import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;

import '../../core/logger/console_logger.dart';
import '../../core/logger/logger.dart';
import '../../core/models/api_endpoint.dart';
import '../../core/models/body_definition.dart';
import '../../core/models/request_log.dart';
import '../../core/resolution/http_client.dart';

class ResendCommand extends Command {
  @override
  String get name => 'resend';

  @override
  String get description =>
      'Re-run a request from a previously generated log file and overwrite '
      'that file with the fresh response.\n\n'
      'Reads the embedded request (method, URL, headers, query, body) from the '
      "log's hidden metadata block, sends it again, and rewrites the same "
      '`.md` file in place with the new status, response and timing.';

  @override
  String get invocation => 'api2dart resend <log-file.md>';

  @override
  void run() async {
    final Logger logger = ConsoleLogger();
    final rest = argResults!.rest;

    if (rest.isEmpty) {
      logger.e('Missing log file. Usage: $invocation');
      exitCode = 64; // EX_USAGE
      return;
    }

    final filePath = rest.first;
    final file = File(filePath);
    if (!file.existsSync()) {
      logger.e('Log file not found: $filePath');
      exitCode = 66; // EX_NOINPUT
      return;
    }

    final content = file.readAsStringSync();
    final source = RequestLog.fromMarkdown(content);
    if (source == null) {
      logger.e('No resend metadata found in $filePath.\n'
          'This file was likely generated by an older version. Re-run '
          '`api2dart generate` to produce a resendable log.');
      exitCode = 65; // EX_DATAERR
      return;
    }

    final method = _parseMethod(source.requestMethod);
    logger.i('Resending ${source.requestMethod} ${source.url}...');

    final httpClient = ApiHttpClient(logger: logger);
    final result = await httpClient.request(
      url: source.url,
      method: method,
      // Headers already carry auth (Authorization / X-Api-Key) verbatim, and
      // the stored URL already includes the query string — so we don't pass
      // queryParams or auth again to avoid duplicating them.
      headers: source.headers.isNotEmpty ? source.headers : null,
      body: _bodyFrom(source.requestBody),
    );

    if (result == null) {
      logger.e('✗ Request failed (no response). File left unchanged.');
      exitCode = 1;
      return;
    }

    final newLog = RequestLog(
      requestName: source.requestName,
      requestMethod: result.requestMethod,
      url: result.requestUrl,
      statusCode: result.statusCode,
      headers: result.requestHeaders,
      queryParameters: result.requestQueryParams,
      requestBody: result.requestBody,
      responseBody: result.body,
      sentTime: result.sentTime,
      receivedTime: result.receivedTime,
    );

    // Overwrite the same file. Keep the original file name in the Resend
    // snippet so the next run still points here.
    final dir = file.parent.path;
    final fileName = p.basenameWithoutExtension(file.path);
    newLog.writeToFile(dir, fileName);

    final ok = result.isSuccess;
    final line = '${ok ? '✓' : '✗'} ${source.requestName} '
        '(${result.statusCode}) → ${file.absolute.path}';
    ok ? logger.i(line) : logger.e(line);
    if (!ok) exitCode = 1;
  }

  HttpMethod _parseMethod(String raw) {
    final upper = raw.toUpperCase();
    return HttpMethod.values.firstWhere(
      (m) => m.name == upper,
      orElse: () => HttpMethod.GET,
    );
  }

  /// Rebuilds a [BodyDefinition] from the logged request body. A `Map` came
  /// from form fields; a non-empty `String` is a raw JSON body.
  BodyDefinition? _bodyFrom(dynamic requestBody) {
    if (requestBody == null) return null;
    if (requestBody is Map) {
      final fields = requestBody
          .map((k, v) => MapEntry(k.toString(), v?.toString() ?? ''));
      if (fields.isEmpty) return null;
      return BodyDefinition(
        contentType: BodyContentType.formData,
        formFields: fields,
      );
    }
    if (requestBody is String && requestBody.isNotEmpty) {
      return BodyDefinition(
        contentType: BodyContentType.rawJson,
        rawBody: requestBody,
      );
    }
    return null;
  }
}
